import type { GameThemeDto } from "./types.js";

export const gameThemes: GameThemeDto[] = [
  { id: "classic-neon", name: "Classic Neon", type: "free", backgroundStyle: "#050816", playerTrailStyle: "#22d3ee", obstacleStyle: "#f43f5e", uiAccentColor: "#22d3ee", particleStyle: "cyan sparks", unlockCondition: "Available to everyone", priceCoins: 0 },
  { id: "dark-space", name: "Dark Space", type: "free", backgroundStyle: "#03040b", playerTrailStyle: "#a78bfa", obstacleStyle: "#fb7185", uiAccentColor: "#a78bfa", particleStyle: "star dust", unlockCondition: "Available to everyone", priceCoins: 0 },
  { id: "cyber-grid", name: "Cyber Grid", type: "free", backgroundStyle: "#07120f", playerTrailStyle: "#4ade80", obstacleStyle: "#facc15", uiAccentColor: "#4ade80", particleStyle: "digital squares", unlockCondition: "Available to everyone", priceCoins: 0 },
  { id: "ocean-blue", name: "Ocean Blue", type: "unlockable", backgroundStyle: "#031b2e", playerTrailStyle: "#38bdf8", obstacleStyle: "#f0f9ff", uiAccentColor: "#0ea5e9", particleStyle: "bubbles", unlockCondition: "Reach 5,000 score or spend 500 coins", priceCoins: 500 },
  { id: "sunset-run", name: "Sunset Run", type: "unlockable", backgroundStyle: "#2d1024", playerTrailStyle: "#fb7185", obstacleStyle: "#fbbf24", uiAccentColor: "#f97316", particleStyle: "sun flares", unlockCondition: "Reach 10,000 score or spend 750 coins", priceCoins: 750 },
  { id: "lava-zone", name: "Lava Zone", type: "unlockable", backgroundStyle: "#1f0705", playerTrailStyle: "#fb923c", obstacleStyle: "#ef4444", uiAccentColor: "#f97316", particleStyle: "embers", unlockCondition: "Reach 15,000 score or spend 1,000 coins", priceCoins: 1000 },
  { id: "ice-world", name: "Ice World", type: "unlockable", backgroundStyle: "#071a2a", playerTrailStyle: "#bae6fd", obstacleStyle: "#60a5fa", uiAccentColor: "#7dd3fc", particleStyle: "snow crystals", unlockCondition: "Reach 20,000 score or spend 1,250 coins", priceCoins: 1250 },
  { id: "forest-glow", name: "Forest Glow", type: "unlockable", backgroundStyle: "#06170f", playerTrailStyle: "#86efac", obstacleStyle: "#fde047", uiAccentColor: "#22c55e", particleStyle: "fireflies", unlockCondition: "Reach 25,000 score or spend 1,500 coins", priceCoins: 1500 },
  { id: "purple-night", name: "Purple Night", type: "unlockable", backgroundStyle: "#16091f", playerTrailStyle: "#d8b4fe", obstacleStyle: "#f472b6", uiAccentColor: "#c084fc", particleStyle: "violet sparks", unlockCondition: "Reach 30,000 score or spend 1,750 coins", priceCoins: 1750 },
  { id: "retro-arcade", name: "Retro Arcade", type: "unlockable", backgroundStyle: "#111827", playerTrailStyle: "#facc15", obstacleStyle: "#ec4899", uiAccentColor: "#22d3ee", particleStyle: "pixel burst", unlockCondition: "Reach 35,000 score or spend 2,000 coins", priceCoins: 2000 },
  { id: "minimal-white", name: "Minimal White", type: "unlockable", backgroundStyle: "#f8fafc", playerTrailStyle: "#0f172a", obstacleStyle: "#e11d48", uiAccentColor: "#0f172a", particleStyle: "ink dots", unlockCondition: "Reach 40,000 score or spend 2,250 coins", priceCoins: 2250 },
  { id: "toxic-green", name: "Toxic Green", type: "unlockable", backgroundStyle: "#071307", playerTrailStyle: "#a3e635", obstacleStyle: "#facc15", uiAccentColor: "#84cc16", particleStyle: "toxic mist", unlockCondition: "Reach 45,000 score or spend 2,500 coins", priceCoins: 2500 },
  { id: "gold-premium", name: "Gold Premium", type: "premium", backgroundStyle: "#171005", playerTrailStyle: "#fde68a", obstacleStyle: "#f59e0b", uiAccentColor: "#fbbf24", particleStyle: "gold shards", unlockCondition: "Premium entitlement", priceCoins: 0 },
  { id: "rainbow-energy", name: "Rainbow Energy", type: "premium", backgroundStyle: "#0d0b1a", playerTrailStyle: "#f0abfc", obstacleStyle: "#67e8f9", uiAccentColor: "#f472b6", particleStyle: "rainbow sparks", unlockCondition: "Premium entitlement", priceCoins: 0 },
  { id: "winter-frost", name: "Winter Frost", type: "unlockable", backgroundStyle: "#0c1b29", playerTrailStyle: "#e0f2fe", obstacleStyle: "#93c5fd", uiAccentColor: "#38bdf8", particleStyle: "frost", unlockCondition: "Reach 50,000 score or spend 2,750 coins", priceCoins: 2750 },
  { id: "desert-storm", name: "Desert Storm", type: "unlockable", backgroundStyle: "#24180a", playerTrailStyle: "#fcd34d", obstacleStyle: "#fb923c", uiAccentColor: "#eab308", particleStyle: "sand grains", unlockCondition: "Reach 55,000 score or spend 3,000 coins", priceCoins: 3000 },
  { id: "candy-mode", name: "Candy Mode", type: "premium", backgroundStyle: "#25112b", playerTrailStyle: "#f9a8d4", obstacleStyle: "#67e8f9", uiAccentColor: "#fb7185", particleStyle: "sugar stars", unlockCondition: "Premium entitlement", priceCoins: 0 },
  { id: "galaxy-trail", name: "Galaxy Trail", type: "premium", backgroundStyle: "#09051b", playerTrailStyle: "#818cf8", obstacleStyle: "#f0abfc", uiAccentColor: "#8b5cf6", particleStyle: "nebula dust", unlockCondition: "Premium entitlement", priceCoins: 0 },
  { id: "matrix-code", name: "Matrix Code", type: "unlockable", backgroundStyle: "#020d06", playerTrailStyle: "#4ade80", obstacleStyle: "#16a34a", uiAccentColor: "#22c55e", particleStyle: "code rain", unlockCondition: "Reach 60,000 score or spend 3,500 coins", priceCoins: 3500 },
  { id: "fire-line", name: "Fire Line", type: "premium", backgroundStyle: "#170604", playerTrailStyle: "#fb923c", obstacleStyle: "#dc2626", uiAccentColor: "#f97316", particleStyle: "flames", unlockCondition: "Premium entitlement", priceCoins: 0 }
];
